class GlobalParams {
  GlobalParams._();

  //supabase_key  url 6T_K*@e*FwXWL5_
  static const String firebaseKey = 'AIzaSyAteU6V1OfMMleH-fM2RHjLuDX9OvdbCGU';
  static const String appId = '1:18357377169:android:751c75c62dabcbf9844730';

  static const String userRealBdPath = "users";

  static const String poliqueOfConfidentialite =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint Praesent euismod, urna in tincidunt gravida, lectus lorem tincidunt justo, nec dignissim neque erat nec magna. Suspendisse potenti. voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint  voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint Curabitur eget mauris non ipsum fermentum volutpat. Integer vitae lectus at orci varius interdum. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nec nisi sed lacus facilisis aliquet. Aliquam erat volutpat. Morbi feugiat, ipsum at facilisis elementum, est magna commodo nulla, sed fermentum lorem sem non odio. Phasellus euismod purus ut mi dignissim, sed dictum lacus vestibulum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.  Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam  aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium";
}
